"""add comment model

Revision ID: ed71a211a1a4
Revises: 6d6cc1abcaa7
Create Date: 2024-10-24 16:18:25.269822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ed71a211a1a4'
down_revision: Union[str, None] = '6d6cc1abcaa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'description',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'description',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
