"""alter course model

Revision ID: d92216f09ba7
Revises: c1adea76a8d9
Create Date: 2024-05-19 15:11:47.129912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd92216f09ba7'
down_revision: Union[str, None] = 'c1adea76a8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'course', ['title'], unique=True)
    # ### end Alembic commands ###
