# Generated by Django 5.1.2 on 2024-10-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('day', models.PositiveSmallIntegerField()),
                ('type', models.PositiveSmallIntegerField()),
                ('site', models.PositiveSmallIntegerField()),
                ('code', models.CharField(max_length=50)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('track', models.PositiveSmallIntegerField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
