# Generated by Django 5.1.2 on 2024-11-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blackboard',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='evaluation',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='interactions',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='lectures',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='recordings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_type',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_accessibility',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='university',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='track',
            field=models.FloatField(default=0),
        ),
    ]
