# Generated by Django 5.1.2 on 2024-11-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_blackboard_course_course_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.TimeField(auto_now=True),
        ),
    ]
