# Generated by Django 5.1.2 on 2024-11-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_end_alter_course_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.TimeField(null=True),
        ),
    ]
