# Generated by Django 5.1.2 on 2024-11-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_end_alter_course_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher_form_filled',
            field=models.BooleanField(default=False),
        ),
    ]
