# Generated by Django 5.1.2 on 2024-11-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tracks',
            field=models.ManyToManyField(to='courses.track'),
        ),
    ]
