# Generated by Django 5.1.2 on 2024-11-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_tracks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='track',
        ),
    ]
