# Generated by Django 5.1.2 on 2024-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blackboard_fb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_type_fb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='evaluation_fb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='interactions_fb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='lectures_fb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='recordings_fb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_type_fb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_accessibility_fb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='university_fb',
            field=models.FloatField(default=0),
        ),
    ]
