# Generated by Django 5.1.2 on 2024-11-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_blackboard_fb_course_course_type_fb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='feedback_count',
            field=models.IntegerField(default=0),
        ),
    ]
