# Generated by Django 5.1.2 on 2024-12-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_rename_user_name_comment_username_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='numeric_code',
            field=models.IntegerField(default=0),
        ),
    ]
