# Generated by Django 5.1.2 on 2024-12-11 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_track_numeric_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_type_fb',
        ),
        migrations.RemoveField(
            model_name='course',
            name='evaluation_fb',
        ),
        migrations.RemoveField(
            model_name='course',
            name='university_fb',
        ),
    ]
