# Generated by Django 5.1.2 on 2024-11-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
